name: Path of Me
description: Blogging about coding
meta_description: "Coding, Objective-C, Blogging about coding"

markdown: redcarpet
pygments: true
logo: false
paginate: 10

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

# Details for the RSS feed generator
url:            'pathof.me'
author:         'Jacky Huang'
